### PR TITLE
OMERO browser switch to default Group and current Owner

### PR DESCRIPTION
**Pull request by melvingelbard**
- OMERO browser now switches directly to the default Group of the current client and the owner corresponding to the current client.
- Fixed missing arg in javadoc.

### CODE REVIEW

**Comment by pwalczysko** [comment]
@melvingelbard unfortunately, the 
``./gradlew clean jpackage`` on this branch ends for me with

```
FAILURE: Build failed with an exception.

* What went wrong:
Task 'jpackage' not found in root project 'qupath-extension-omero'.
```

I guess I would need a built artifact from you to be able to help with testing I am afraid.

**Comment by melvingelbard** [comment]
@pwalczysko Have you tried with `./gradlew clean build` instead?

**Comment by pwalczysko** [comment]
> @pwalczysko Have you tried with `./gradlew clean build` instead?

Yes, that worked, thanks, testing now.

**Comment by pwalczysko** [comment]
Tested the extension from this PR on Mac with QuPath v0.3.0.
The workflow was https://omero-guides.readthedocs.io/en/latest/qupath/docs/qupath.html - except I saved to OMERO and reopened several times. All worked fine, could not see any regression.

As for the new feature, works as expected, the default group is on display and only the data of the logged-in user are displayed by default. The selection of images belonging to other users as well as other groups works fine too.

1 comments:

The user list does not seem to be alphabetically or otherwise ordered, which makes it a bit difficult to find other user names.
Screenshot 2021-11-12 at 16 06 02

**Pull request merged**
